name: IaC - VNet - OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deployVNet"
  deployVNet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: RepoCheckout
        uses: actions/checkout@v6.0.0
        
      - name: Azure Login
        uses: Azure/login@v3
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZ_IAC_SP }}

      - name: DeployBicep
        uses: Azure/bicep-deploy@v2.3.0
        with:
          # Specifies the execution type, which can be either 'deployment' or 'deploymentStack'.
          type: deployment
          # Specifies the Azure subscription ID to which the deployment will be applied.
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          # Specifies the operation to perform. For deployment, choose from 'create', 'validate', 'whatIf'. For deploymentStack, choose from 'create', 'delete', 'validate'.
          operation: create
          # Specifies the scope of the deployment or deploymentStack. For deployment, choose from 'resourceGroup', 'subscription', 'managementGroup', 'tenant'. For deploymentStack, choose from 'resourceGroup', 'subscription', 'managementGroup'.
          scope: resourceGroup 
          # Specifies the name of the deployment or deploymentStack.
          name: ghaDeploment
          # Specifies the resource group name. Required if the 'scope' parameter is 'resourceGroup'.
          resource-group-name: RG-IaC-Mighel
          # Specifies the path to the template file.
          template-file: ./VNet.bicep
